
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AnalysisResult, AnalysisFocus } from '../types';

export const generateClinicalReport = (
  result: AnalysisResult, 
  inputDataSnippet: string, 
  focusAreas: AnalysisFocus[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  
  // Helpers
  const generateReportId = () => {
    return `#SIM-${new Date().getFullYear()}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`;
  };
  const reportId = generateReportId();
  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // === WATERMARK ===
  doc.setTextColor(230, 230, 230);
  doc.setFontSize(50);
  doc.setFont("helvetica", "bold");
  doc.text("SIMULATION ONLY", pageWidth / 2, 100, { align: "center", angle: 45 });
  doc.text("NOT FOR MEDICAL USE", pageWidth / 2, 180, { align: "center", angle: 45 });

  // === HEADER ===
  // Red Alert Banner
  doc.setFillColor(200, 0, 0);
  doc.rect(0, 0, pageWidth, 15, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("WARNING: THIS REPORT IS GENERATED BY AI FOR RESEARCH SIMULATION. DO NOT USE FOR DIAGNOSIS.", pageWidth / 2, 10, { align: "center" });

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("ABK Genomics Core", margin, 35);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text("Genomic Research Simulation Report", margin, 43);

  // Right Header info
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(currentDate, pageWidth - margin, 35, { align: "right" });
  doc.text(reportId, pageWidth - margin, 40, { align: "right" });

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 50, pageWidth - margin, 50);

  // === SECTION 1: CONTEXT ===
  let yPos = 60;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text("SECTION 1: SIMULATION CONTEXT", margin, yPos);
  
  yPos += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Input Data Snippet:", margin, yPos);
  
  doc.setFont("helvetica", "normal");
  const cleanInput = inputDataSnippet.length > 120 
    ? inputDataSnippet.substring(0, 120).replace(/\n/g, " ") + "..." 
    : inputDataSnippet.replace(/\n/g, " ");
  
  doc.text(cleanInput, margin + 45, yPos);

  yPos += 6;
  doc.setFont("helvetica", "bold");
  doc.text("Focus Areas:", margin, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(focusAreas.join(", "), margin + 45, yPos);

  // === SECTION 2: AI INTERPRETATION ===
  yPos += 15;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("SECTION 2: AI-GENERATED SUMMARY (UNVERIFIED)", margin, yPos);
  
  yPos += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  const summaryLines = doc.splitTextToSize(result.patientSummary, pageWidth - (margin * 2));
  doc.text(summaryLines, margin, yPos);
  yPos += (summaryLines.length * 5) + 5;

  // === SECTION 3: KEY FINDINGS (TABLE) ===
  yPos += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("SECTION 3: DETECTED VARIANTS", margin, yPos);

  const tableBody = result.variants.map(v => [
    v.gene,
    v.variant,
    v.riskLevel,
    v.clinVarSignificance || "N/A"
  ]);

  if (tableBody.length === 0) {
      tableBody.push(["No significant variants detected", "-", "-", "-"]);
  }

  autoTable(doc, {
    startY: yPos + 5,
    head: [['GENE', 'VARIANT', 'RISK LABEL', 'CLINVAR (REAL)']],
    body: tableBody,
    theme: 'grid',
    headStyles: { fillColor: [50, 50, 50], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
        0: { fontStyle: 'bold' },
        3: { fontStyle: 'italic', textColor: [0, 100, 0] } // Green for real data
    }
  });

  // @ts-ignore
  let finalY = doc.lastAutoTable.finalY || yPos + 20;

  // === DISCLAIMER FOOTER ===
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageHeight = doc.internal.pageSize.height;
      
      doc.setFontSize(8);
      
      // Left
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by ABK Genomics Simulation Core.", margin, pageHeight - 10);
      
      // Right - Legal
      doc.setTextColor(200, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text("EDUCATIONAL USE ONLY. NOT FOR CLINICAL DIAGNOSIS.", pageWidth - margin, pageHeight - 10, { align: "right" });
  }

  doc.save(`Simulation_Report_${reportId.replace('#', '')}.pdf`);
};
